#spring.application.name=SpringBootRestJPAMySQL

spring:
  application:
    name: SpringBootRestJPAMySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mlamarch1
    username: root
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    deserialization:
      fail-on-null-for-primitives: false

debug: true

server:
  port: 7799

#logging

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO
  file:
    path: logs/
    name: logs/application.log


#actuator configuration
#metrics, info, health, env, beans, mappings, loggers, threaddump, heapdump, shutdown etc.
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always


